### ISSUE TITLE
EMS Lights Issues - Error and Missing Lights

### ISSUE THREAD

**Issue by NSG-Cyanide** [EasysAltisLife/Easys-Altis-Life#29]
Apparently it doesn't work all the time on the hatchbacks and SUVS are missing all lights as well.

**Comment by imthatguyhere** [comment]
## Issue Summary:

Medic vehicles have no option to turn on or off the lights separately. Due to this the lights and siren get out of sync when getting out with the sirens on. (The lights stay on but the sirens are off and you have to get back in, turn on sirens and get out to get both off again and it to be back in sync).

EMS SUV's are also missing lights altogether.

### Proposed Solution:

Add a dedicated hot-key to switch lights on and off like the police have (Ctrl+L).

Also add lights to the EMS SUV.

**EDIT: It seems that the Hatchback Sport is also missing lights randomly, sometimes they work and sometimes they don't.**

**Comment by trypants** [comment]
fixed
