### ISSUE TITLE
Stuck in Group

### ISSUE THREAD

**Issue by Exhil** [EasysAltisLife/Easys-Altis-Life#40]
I joined my friend's gang a while ago but now when I join another gang and relog it puts me back in that group. I tried syncing data after leaving and after joining the other group but nothing has helped.

**Comment by imthatguyhere** [comment]
## Issue Summary

This issue occurs when a user leaves a gang and it doesn't get disbanded. If the original gang gets disbanded, this is not an issue.

### Cause

The code pulls the first occurrence of the user's steamid (playerid) from the database and checks if the gang is still active. When a user leaves a gang they do not get removed from the list of members in the database. Due to this the first gang found is the one the user gets stuck in.

### Solution

Until we get a fix for the code, post a topic here: [Easy's Altis Life: Help Desk](http://forum.a3lrp.org/index.php?/forum/20-help-desk/).

#### Make sure to include your playerid and the gang you are stuck in in the post.

**Comment by EliteBanana** [comment]
I THINK i have found a solution for this issue. As a gang leader, I would tel the person to leave the gang > sync data > join gang > sync data again. This would keep the player in the gang he was last in before leaving the server.

**Comment by s1k-altisLife** [comment]
I will do some testing on it. Let me know if that infact works.  The problem actually is having the DELETE query be safe and not exploitable to wipe our entire DB if you're a real hacker and know what you're doing. I "could" fix it right now with a simple delete query, but we all know you cant trust people, lol. <3.

**Comment by imthatguyhere** [comment]
Should be improved in the next few patches.
