### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by MyMatt444** [EasysAltisLife/Easys-Altis-Life#69]
It's literally unplayable. Want to drug runs? You cant because everytime you try the server crashes. I was told a week ago this was being fixed the next day yet it still is broken. Your server is beyond unplayable for people wishing to do drug runs/apple runs/gold runs etc. Stop delaying this please!

**Comment by imthatguyhere** [comment]
## These Crashes are due to Bohemia, please follow their bug tracker to see our battle:
- [Roll-Back Petition](http://feedback.arma3.com/view.php?id=26924)
- [Dedicated Server Crashing](http://feedback.arma3.com/view.php?id=26863)
- [Increasing Memory Leaks / Errors](http://feedback.arma3.com/view.php?id=25493)
- [Crashing Since 1.54](http://feedback.arma3.com/view.php?id=26925)
- [And Many, Many More](http://feedback.arma3.com/view_all_bug_page.php)
- [Crashing After Dev Patch](http://feedback.arma3.com/view.php?id=26878)

### [We have official word on it here](http://forum.a3lrp.org/index.php?/topic/5299-addressing-armas-154-patch-instability-and-crashing/#entry15718)

I think there's a huge misconception here. We have not stopped work on attempting to increase stability since the Arma 1.54 patch. Also we aren't causing or in control of the crashes.

Bohemia released Arma 3 1.54 and it introduced sprinting issues, uniforms disappearing, players phasing in and out of existence and the server crashes. These crashes do not generate user dumps, and don't put any usable information into the RPT for us to diagnose these problems. It's thought to be a memory leak and we have been trying to test different Memory Allocators to see if they can last longer before crashing the server. When the server is full it's 1hr up with a +/- 15 minute delta.

These issues are tested occurring on Every branch of Altis Life 3.x 4.x and 5.x. We are trying to blindly figure out what's at issue without any help from Bohemia or any way to find out provided by Bohemia. It's like trying to reinvent the wheel for aliens that won't tell us how they use wheels or how they attach to their vehicles.

We will eventually solve these issues on our own through trial and error but a quick bugfix from Bohemia or a rollback would be the best bet for the Altis Life Community. If you care so much about this community as we do, go the to bug trackers listed at the top and vote them up.
